-- ============================================================
-- 寻道大千 · 数据库升级脚本 v6
-- 逐日签到记录 + 原子签到。
-- 幂等设计：可重复执行。
-- ============================================================

CREATE TABLE IF NOT EXISTS daily_checkins (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_role TEXT NOT NULL DEFAULT 'player',
  checkin_date DATE NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (user_role, checkin_date)
);

-- 将旧结构中还能确认的最后一次签到补入历史表。
INSERT INTO daily_checkins (user_role, checkin_date)
SELECT user_role, last_daily_date
FROM player_state
WHERE last_daily_date IS NOT NULL
ON CONFLICT (user_role, checkin_date) DO NOTHING;

ALTER TABLE daily_checkins ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE daily_checkins FROM anon, authenticated;

CREATE OR REPLACE FUNCTION daily_check_in()
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_today DATE := (NOW() AT TIME ZONE 'Asia/Shanghai')::DATE;
  v_month TEXT := TO_CHAR(v_today, 'YYYY-MM');
  v_month_start DATE := DATE_TRUNC('month', v_today::TIMESTAMP)::DATE;
  v_inserted_id BIGINT;
  v_days INTEGER;
  v_chopping_count INTEGER;
  v_claims JSONB;
BEGIN
  PERFORM 1
  FROM player_state
  WHERE user_role = 'player'
  FOR UPDATE;

  IF NOT FOUND THEN
    RETURN jsonb_build_object('ok', false, 'code', 'player_not_found');
  END IF;

  INSERT INTO daily_checkins (user_role, checkin_date)
  VALUES ('player', v_today)
  ON CONFLICT (user_role, checkin_date) DO NOTHING
  RETURNING id INTO v_inserted_id;

  SELECT COUNT(*)::INTEGER
  INTO v_days
  FROM daily_checkins
  WHERE user_role = 'player'
    AND checkin_date >= v_month_start
    AND checkin_date < (v_month_start + INTERVAL '1 month')::DATE;

  UPDATE player_state
  SET chopping_count = chopping_count + CASE WHEN v_inserted_id IS NULL THEN 0 ELSE 1 END,
      last_daily_date = v_today,
      signin_month = v_month,
      signin_days = v_days,
      signin_claims = CASE
        WHEN signin_month IS DISTINCT FROM v_month THEN '[]'::JSONB
        ELSE COALESCE(signin_claims, '[]'::JSONB)
      END,
      updated_at = NOW()
  WHERE user_role = 'player'
  RETURNING chopping_count, signin_claims
  INTO v_chopping_count, v_claims;

  RETURN jsonb_build_object(
    'ok', v_inserted_id IS NOT NULL,
    'code', CASE WHEN v_inserted_id IS NULL THEN 'already_checked' ELSE 'ok' END,
    'date', v_today,
    'month', v_month,
    'days', v_days,
    'choppingCount', v_chopping_count,
    'claims', COALESCE(v_claims, '[]'::JSONB)
  );
END;
$$;

REVOKE ALL ON FUNCTION daily_check_in() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION daily_check_in() TO anon, authenticated;
